defaults:
  - default_dataset.yaml

exp_name: test_example
img_size: 518
num_workers: 8
# num_workers: 0 # debug only
seed_value: 42
# accum_steps: 2   
accum_steps: 1    
patch_size: 14
val_epoch_freq: 2
max_img_per_gpu: 12

limit_train_batches: 1000
limit_val_batches: 20


data:
  # The code for data still looks too complicated. I should refactor this again (do I have time?...)
  train:
    _target_: data.dynamic_dataloader.DynamicTorchDataset
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_size: ${img_size}
      patch_size: ${patch_size}
      debug: True
      repeat_batch: False
    dataset:
      _target_: data.composed_intrinsic_dataset.ComposedIntrinsicDataset
      dataset_configs:
        - _target_: data.datasets.interiorverse.InteriorverseDataset
          split: train
          Interiorverse_DIR: /home/data/wxz/projects/mvinverse/datasets/interiorverse
  val:
    _target_: data.dynamic_dataloader.DynamicTorchDataset
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_size: ${img_size}
      patch_size: ${patch_size}
      debug: True
    dataset:
      _target_: data.composed_intrinsic_dataset.ComposedIntrinsicDataset
      dataset_configs:
        - _target_: data.datasets.interiorverse.InteriorverseDataset
          split: test
          Interiorverse_DIR: /home/data/wxz/projects/mvinverse/datasets/interiorverse


logging:
  log_dir: logs/${exp_name}
  log_visuals: False
  log_freq: 1
  log_level_primary: DEBUG
  log_level_secondary: WARNING
  all_ranks: False
  tensorboard_writer:
    _target_: train_utils.tb_writer.TensorBoardLogger
    path: ${logging.log_dir}/tensorboard
  scalar_keys_to_log:
    train:
      keys_to_log:
        - loss_objective
        - loss_reg_albedo
        - loss_grad_albedo
        - loss_reg_metallic
        - loss_grad_metallic
        - loss_reg_roughness
        - loss_grad_roughness
        - loss_negcos_normal
    val:
      keys_to_log:
        - loss_objective
        - loss_reg_albedo
        - loss_grad_albedo
        - loss_reg_metallic
        - loss_grad_metallic
        - loss_reg_roughness
        - loss_grad_roughness
        - loss_negcos_normal


checkpoint:
  save_dir: logs/${exp_name}/ckpts
  val_dir: logs/${exp_name}/vals
  save_freq: 5
  resume_checkpoint_path: /home/data/wxz/projects/mvinverse/ckpts/model.safetensors
  strict: False


loss:
  _target_: loss.MultitaskLoss
  albedo:
    reg_weight: 1.0
    grad_weight: 1.0
  metallic:
    reg_weight: 1.0
    grad_weight: 1.0
  roughness:
    reg_weight: 1.0
    grad_weight: 1.0
  normal:
    weight: 1.0
  shading:
    reg_weight: 1.0
    grad_weight: 1.0



optim:
  param_group_modifiers: False

  optimizer:
    _target_: torch.optim.AdamW
    lr: 5e-5
    weight_decay: 0.05

  frozen_module_names:
      - "encoder"
      - "res_encoder"
      # - "decoder"
      # - "decoder[0:12]"
      # - "albedo_head"
      # - "metallic_head"
      # - "roughness_head"
      # - "normal_head"
      # - "shading_head"
  
  freeze_register: False

  amp:
    enabled: True
    amp_dtype: bfloat16
  gradient_clip:
    _target_: train_utils.gradient_clip.GradientClipper
    # 
    configs:
      - module_name: ["encoder"]
        max_norm: 1.0   # feel free to reduce this if you see instabilities
        norm_type: 2
      - module_name: ["decoder"]
        max_norm: 1.0   # feel free to reduce this if you see instabilities
        norm_type: 2
      - module_name: ["head"]
        max_norm: 1.0   # feel free to reduce this if you see instabilities
        norm_type: 2
      - module_name: ["register_token"]
        max_norm: 1.0   # feel free to reduce this if you see instabilities
        norm_type: 2
  options:
    lr:
      - scheduler:
          _target_: fvcore.common.param_scheduler.CompositeParamScheduler
          schedulers:
            - _target_: fvcore.common.param_scheduler.LinearParamScheduler
              start_value: 1e-8
              end_value: 5e-5
            - _target_: fvcore.common.param_scheduler.CosineParamScheduler
              start_value: 5e-5
              end_value: 1e-8
          lengths: [0.05, 0.95]
          interval_scaling: ['rescaled', 'rescaled']
    weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.05




max_epochs: 200

model:
  _target_: mvinverse.models.mvinverse.MVInverse


distributed:
  # check https://docs.pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html for options
  backend: nccl
  comms_dtype: None
  find_unused_parameters: False
  timeout_mins: 30
  gradient_as_bucket_view: True  # Less memory used
  bucket_cap_mb: 25
  broadcast_buffers: True

cuda:
    cudnn_deterministic: False
    cudnn_benchmark: False
    allow_tf32: True